### PR TITLE
Istio sidecar, limits for cosmos

### PR DESCRIPTION
**Pull request by sivamu**
# Type of PR

- [ ] Documentation changes
- [x] Code changes
- [ ] Test changes
- [ ] CI-CD changes
- [ ] GitHub Template changes

## PR Checklist

- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] My code follows the code style of this project.
- [ ] I ran lint checks locally prior to submission.
- [ ] Have you checked to ensure there aren't other open Pull Requests for the same update/change?

## Purpose of PR
Enable istio sidecar for dev cosmos only
Add Istio sidecar requests/limits where sidecar deployed
Ngsa memory shouldn't use npuser01 node

## Does this introduce a breaking change

- [ ] YES
- [x] NO

## Issues Closed or Referenced
- References https://github.com/retaildevcrews/wcnp/issues/1016

### CODE REVIEW

**Review by gortegaMS — APPROVED** [review]
LGTM

**Comment by kforeverisback** [comment]
@sivamu and @gortegaMS We have a PR to change istio-proxy resource usage in our PR as well.

But we use the YAML strategic merge method instead of annotations.
Do you think we should discuss which method to go with?

Also, is there any reason why ngsa-memory should not be in `npuser01` node?

**Comment by sivamu** [comment]
> Also, is there any reason why ngsa-memory should not be in npuser01 node?
ngsa-memory doesn't need pod identity secret injection so no reason for npuser01

**Comment by sivamu** [comment]
Closing this PR. will go with the YAML merge method to override istio values which will make it easier for future changes to the sidecar

**Pull request closed without merging**
